### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Cregin** [SmileZXLee/ZXBlockLog#2]
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 1'
	*** First throw call stack:
	(0x185600f5c 0x19aae7f80 0x185600ea4 0x1855e8670 0x104d61548 0x104d8aac0 0x104ef530c 0x104e67d60 0x1008f423c 0x1008f4498 0x1006000e8 0x18b0afb28 0x18acf6a5c 0x18ab896ac 0x18b0b0e78 0x18ab49118 0x18ab471ec 0x18ab87564 0x18ab86ac8 0x102b56504 0x18ab57a2c 0x18ab55f18 0x1855b85a4 0x1855b8038 0x1855b5d38 0x1854e4dc0 0x190980088 0x18abbef60 0x100081970 0x19b3068b8)

**Comment by SmileZXLee** [comment]
您好，感谢反馈，可以劳烦您协助调试一下吗，以便我确定问题的原因，在"ZXBlockLogTool.m"中第15行打一个断点，或直接NSLog一下typeStr的值，谢谢您。

**Comment by SmileZXLee** [comment]
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 1'
> *** First throw call stack:
> (0x185600f5c 0x19aae7f80 0x185600ea4 0x1855e8670 0x104d61548 0x104d8aac0 0x104ef530c 0x104e67d60 0x1008f423c 0x1008f4498 0x1006000e8 0x18b0afb28 0x18acf6a5c 0x18ab896ac 0x18b0b0e78 0x18ab49118 0x18ab471ec 0x18ab87564 0x18ab86ac8 0x102b56504 0x18ab57a2c 0x18ab55f18 0x1855b85a4 0x1855b8038 0x1855b5d38 0x1854e4dc0 0x190980088 0x18abbef60 0x100081970 0x19b3068b8)

您好，感谢反馈，可以劳烦您协助调试一下吗，以便我确定问题的原因，在"ZXBlockLogTool.m"中第15行打一个断点，或直接NSLog一下typeStr的值，谢谢您。

**Comment by SmileZXLee** [comment]
已修复这一问题，您可以更新一下。
